# Form implementation generated from reading ui file 'AttributionWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AttributionWindow(object):
    def setupUi(self, AttributionWindow):
        AttributionWindow.setObjectName("AttributionWindow")
        AttributionWindow.resize(495, 301)
        self.centralwidget = QtWidgets.QWidget(parent=AttributionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        AttributionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AttributionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 495, 21))
        self.menubar.setObjectName("menubar")
        AttributionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AttributionWindow)
        self.statusbar.setObjectName("statusbar")
        AttributionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AttributionWindow)
        QtCore.QMetaObject.connectSlotsByName(AttributionWindow)

    def retranslateUi(self, AttributionWindow):
        _translate = QtCore.QCoreApplication.translate
        AttributionWindow.setWindowTitle(_translate("AttributionWindow", "Icon Attribution"))
        self.label.setText(_translate("AttributionWindow", "Icons used in this application by Yusuke Kamiyamane from https://p.yusukekamiyamane.com/, licensed under Creative Commons Attribution 3.0. (View the license terms at https://creativecommons.org/licenses/by/3.0/)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttributionWindow = QtWidgets.QMainWindow()
    ui = Ui_AttributionWindow()
    ui.setupUi(AttributionWindow)
    AttributionWindow.show()
    sys.exit(app.exec())