# Form implementation generated from reading ui file 'ConvertWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConvertWindow(object):
    def setupUi(self, ConvertWindow):
        ConvertWindow.setObjectName("ConvertWindow")
        ConvertWindow.resize(461, 182)
        self.centralwidget = QtWidgets.QWidget(parent=ConvertWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.selectPathButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.selectPathButton.setObjectName("selectPathButton")
        self.gridLayout.addWidget(self.selectPathButton, 0, 0, 1, 1)
        self.folderPath = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.folderPath.setReadOnly(True)
        self.folderPath.setObjectName("folderPath")
        self.gridLayout.addWidget(self.folderPath, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.convertButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.convertButton.setObjectName("convertButton")
        self.gridLayout_2.addWidget(self.convertButton, 2, 0, 1, 2)
        self.splitCreateBtn = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.splitCreateBtn.setChecked(True)
        self.splitCreateBtn.setObjectName("splitCreateBtn")
        self.gridLayout_2.addWidget(self.splitCreateBtn, 1, 0, 1, 1)
        self.splitDirectBtn = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.splitDirectBtn.setObjectName("splitDirectBtn")
        self.gridLayout_2.addWidget(self.splitDirectBtn, 1, 1, 1, 1)
        ConvertWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ConvertWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 21))
        self.menubar.setObjectName("menubar")
        ConvertWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ConvertWindow)
        self.statusbar.setObjectName("statusbar")
        ConvertWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConvertWindow)
        QtCore.QMetaObject.connectSlotsByName(ConvertWindow)

    def retranslateUi(self, ConvertWindow):
        _translate = QtCore.QCoreApplication.translate
        ConvertWindow.setWindowTitle(_translate("ConvertWindow", "File conversion"))
        self.selectPathButton.setText(_translate("ConvertWindow", "Select path"))
        self.convertButton.setText(_translate("ConvertWindow", "Convert"))
        self.splitCreateBtn.setText(_translate("ConvertWindow", "Split data for training data creation"))
        self.splitDirectBtn.setText(_translate("ConvertWindow", "Split data for direct output"))
