# Form implementation generated from reading ui file 'CreateWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateWindow(object):
    def setupUi(self, CreateWindow):
        CreateWindow.setObjectName("CreateWindow")
        CreateWindow.resize(461, 155)
        self.centralwidget = QtWidgets.QWidget(parent=CreateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.selectPathButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.selectPathButton.setObjectName("selectPathButton")
        self.gridLayout.addWidget(self.selectPathButton, 0, 0, 1, 1)
        self.folderPath = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.folderPath.setReadOnly(True)
        self.folderPath.setObjectName("folderPath")
        self.gridLayout.addWidget(self.folderPath, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.generateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generateButton.setObjectName("generateButton")
        self.verticalLayout.addWidget(self.generateButton)
        CreateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CreateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 21))
        self.menubar.setObjectName("menubar")
        CreateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CreateWindow)
        self.statusbar.setObjectName("statusbar")
        CreateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CreateWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateWindow)

    def retranslateUi(self, CreateWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateWindow.setWindowTitle(_translate("CreateWindow", "Traning data creation"))
        self.selectPathButton.setText(_translate("CreateWindow", "Select path"))
        self.generateButton.setText(_translate("CreateWindow", "Generate training data"))
