# Form implementation generated from reading ui file 'SplitWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SplitWindow(object):
    def setupUi(self, SplitWindow):
        SplitWindow.setObjectName("SplitWindow")
        SplitWindow.resize(461, 155)
        self.centralwidget = QtWidgets.QWidget(parent=SplitWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.selectPathButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.selectPathButton.setObjectName("selectPathButton")
        self.gridLayout.addWidget(self.selectPathButton, 0, 0, 1, 1)
        self.folderPath = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.folderPath.setReadOnly(True)
        self.folderPath.setObjectName("folderPath")
        self.gridLayout.addWidget(self.folderPath, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.splitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.splitButton.setObjectName("splitButton")
        self.verticalLayout.addWidget(self.splitButton)
        SplitWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SplitWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 21))
        self.menubar.setObjectName("menubar")
        SplitWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SplitWindow)
        self.statusbar.setObjectName("statusbar")
        SplitWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SplitWindow)
        QtCore.QMetaObject.connectSlotsByName(SplitWindow)

    def retranslateUi(self, SplitWindow):
        _translate = QtCore.QCoreApplication.translate
        SplitWindow.setWindowTitle(_translate("SplitWindow", "Data splitting"))
        self.selectPathButton.setText(_translate("SplitWindow", "Select path"))
        self.splitButton.setText(_translate("SplitWindow", "Split"))
